# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1200, 800)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbox = QtWidgets.QToolBox(self.central_widget)
        self.toolbox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toolbox.setObjectName("toolbox")
        self.comparision_toolbox = QtWidgets.QWidget()
        self.comparision_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.comparision_toolbox.setObjectName("comparision_toolbox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.comparision_toolbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comparision_filters_group = QtWidgets.QGroupBox(self.comparision_toolbox)
        self.comparision_filters_group.setObjectName("comparision_filters_group")
        self.formLayout_4 = QtWidgets.QFormLayout(self.comparision_filters_group)
        self.formLayout_4.setObjectName("formLayout_4")
        self.comparision_filters_prefixes_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_prefixes_label.setObjectName("comparision_filters_prefixes_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_prefixes_label)
        self.comparision_filters_prefixes_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_prefixes_text.setObjectName("comparision_filters_prefixes_text")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_prefixes_text)
        self.comparision_filters_names_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_names_label.setObjectName("comparision_filters_names_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_names_label)
        self.comparision_filters_categories_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_categories_label.setObjectName("comparision_filters_categories_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_categories_label)
        self.comparision_filters_colors_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_colors_label.setObjectName("comparision_filters_colors_label")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_colors_label)
        self.comparision_filters_sizes_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_sizes_label.setObjectName("comparision_filters_sizes_label")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_sizes_label)
        self.comparision_filters_sexes_label = QtWidgets.QLabel(self.comparision_filters_group)
        self.comparision_filters_sexes_label.setObjectName("comparision_filters_sexes_label")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.comparision_filters_sexes_label)
        self.comparision_filters_names_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_names_text.setObjectName("comparision_filters_names_text")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_names_text)
        self.comparision_filters_categories_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_categories_text.setObjectName("comparision_filters_categories_text")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_categories_text)
        self.comparision_filters_colors_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_colors_text.setObjectName("comparision_filters_colors_text")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_colors_text)
        self.comparision_filters_sizes_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_sizes_text.setObjectName("comparision_filters_sizes_text")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_sizes_text)
        self.comparision_filters_sexes_text = QtWidgets.QLineEdit(self.comparision_filters_group)
        self.comparision_filters_sexes_text.setObjectName("comparision_filters_sexes_text")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comparision_filters_sexes_text)
        self.verticalLayout_5.addWidget(self.comparision_filters_group, 0, QtCore.Qt.AlignTop)
        self.comparision_periods_group = QtWidgets.QGroupBox(self.comparision_toolbox)
        self.comparision_periods_group.setObjectName("comparision_periods_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.comparision_periods_group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comparision_periods_text = QtWidgets.QPlainTextEdit(self.comparision_periods_group)
        self.comparision_periods_text.setMaximumSize(QtCore.QSize(16777215, 70))
        self.comparision_periods_text.setPlaceholderText("YYYY-MM-DD YYYY-MM-DD")
        self.comparision_periods_text.setObjectName("comparision_periods_text")
        self.verticalLayout_4.addWidget(self.comparision_periods_text)
        self.verticalLayout_5.addWidget(self.comparision_periods_group, 0, QtCore.Qt.AlignTop)
        self.comparision_income_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_income_button.setObjectName("comparision_income_button")
        self.verticalLayout_5.addWidget(self.comparision_income_button)
        self.comparision_costs_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_costs_button.setObjectName("comparision_costs_button")
        self.verticalLayout_5.addWidget(self.comparision_costs_button)
        self.comparision_income_balance_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_income_balance_button.setObjectName("comparision_income_balance_button")
        self.verticalLayout_5.addWidget(self.comparision_income_balance_button)
        self.comparision_sales_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_sales_button.setObjectName("comparision_sales_button")
        self.verticalLayout_5.addWidget(self.comparision_sales_button)
        self.comparision_resupply_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_resupply_button.setObjectName("comparision_resupply_button")
        self.verticalLayout_5.addWidget(self.comparision_resupply_button)
        self.comparision_operations_balance_button = QtWidgets.QPushButton(self.comparision_toolbox)
        self.comparision_operations_balance_button.setObjectName("comparision_operations_balance_button")
        self.verticalLayout_5.addWidget(self.comparision_operations_balance_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.toolbox.addItem(self.comparision_toolbox, "")
        self.balance_toolbox = QtWidgets.QWidget()
        self.balance_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.balance_toolbox.setObjectName("balance_toolbox")
        self.gridLayout = QtWidgets.QGridLayout(self.balance_toolbox)
        self.gridLayout.setObjectName("gridLayout")
        self.balance_incomes_button = QtWidgets.QPushButton(self.balance_toolbox)
        self.balance_incomes_button.setObjectName("balance_incomes_button")
        self.gridLayout.addWidget(self.balance_incomes_button, 1, 0, 1, 1)
        self.balance_operations_button = QtWidgets.QPushButton(self.balance_toolbox)
        self.balance_operations_button.setObjectName("balance_operations_button")
        self.gridLayout.addWidget(self.balance_operations_button, 2, 0, 1, 1)
        self.balance_year_group = QtWidgets.QGroupBox(self.balance_toolbox)
        self.balance_year_group.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.balance_year_group.setObjectName("balance_year_group")
        self.formLayout_3 = QtWidgets.QFormLayout(self.balance_year_group)
        self.formLayout_3.setObjectName("formLayout_3")
        self.balance_year_from_label = QtWidgets.QLabel(self.balance_year_group)
        self.balance_year_from_label.setObjectName("balance_year_from_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.balance_year_from_label)
        self.balance_year_from_spinbox = QtWidgets.QSpinBox(self.balance_year_group)
        self.balance_year_from_spinbox.setMinimum(2012)
        self.balance_year_from_spinbox.setMaximum(2020)
        self.balance_year_from_spinbox.setObjectName("balance_year_from_spinbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.balance_year_from_spinbox)
        self.balance_year_to_label = QtWidgets.QLabel(self.balance_year_group)
        self.balance_year_to_label.setObjectName("balance_year_to_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.balance_year_to_label)
        self.balance_year_to_spinbox = QtWidgets.QSpinBox(self.balance_year_group)
        self.balance_year_to_spinbox.setMinimum(2012)
        self.balance_year_to_spinbox.setMaximum(2020)
        self.balance_year_to_spinbox.setProperty("value", 2020)
        self.balance_year_to_spinbox.setObjectName("balance_year_to_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.balance_year_to_spinbox)
        self.gridLayout.addWidget(self.balance_year_group, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.toolbox.addItem(self.balance_toolbox, "")
        self.stock_toolbox = QtWidgets.QWidget()
        self.stock_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.stock_toolbox.setObjectName("stock_toolbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stock_toolbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stock_filters_group = QtWidgets.QGroupBox(self.stock_toolbox)
        self.stock_filters_group.setObjectName("stock_filters_group")
        self.formLayout_5 = QtWidgets.QFormLayout(self.stock_filters_group)
        self.formLayout_5.setObjectName("formLayout_5")
        self.stock_filters_prefixes_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_prefixes_label.setObjectName("stock_filters_prefixes_label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stock_filters_prefixes_label)
        self.stock_filters_prefixes_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_prefixes_text.setObjectName("stock_filters_prefixes_text")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stock_filters_prefixes_text)
        self.stock_filters_names_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_names_label.setObjectName("stock_filters_names_label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stock_filters_names_label)
        self.stock_filters_names_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_names_text.setObjectName("stock_filters_names_text")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stock_filters_names_text)
        self.stock_filters_categories_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_categories_label.setObjectName("stock_filters_categories_label")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stock_filters_categories_label)
        self.stock_filters_categories_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_categories_text.setObjectName("stock_filters_categories_text")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stock_filters_categories_text)
        self.stock_filters_colors_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_colors_label.setObjectName("stock_filters_colors_label")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.stock_filters_colors_label)
        self.stock_filters_colors_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_colors_text.setObjectName("stock_filters_colors_text")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stock_filters_colors_text)
        self.stock_filters_sizes_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_sizes_label.setObjectName("stock_filters_sizes_label")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stock_filters_sizes_label)
        self.stock_filters_sizes_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_sizes_text.setObjectName("stock_filters_sizes_text")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stock_filters_sizes_text)
        self.stock_filters_sexes_label = QtWidgets.QLabel(self.stock_filters_group)
        self.stock_filters_sexes_label.setObjectName("stock_filters_sexes_label")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.stock_filters_sexes_label)
        self.stock_filters_sexes_text = QtWidgets.QLineEdit(self.stock_filters_group)
        self.stock_filters_sexes_text.setObjectName("stock_filters_sexes_text")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.stock_filters_sexes_text)
        self.verticalLayout_2.addWidget(self.stock_filters_group, 0, QtCore.Qt.AlignTop)
        self.stock_date_group = QtWidgets.QGroupBox(self.stock_toolbox)
        self.stock_date_group.setObjectName("stock_date_group")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stock_date_group)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stock_date = QtWidgets.QDateEdit(self.stock_date_group)
        self.stock_date.setMinimumDate(QtCore.QDate(2012, 1, 1))
        self.stock_date.setObjectName("stock_date")
        self.verticalLayout_6.addWidget(self.stock_date)
        self.verticalLayout_2.addWidget(self.stock_date_group, 0, QtCore.Qt.AlignTop)
        self.stock_color_button = QtWidgets.QPushButton(self.stock_toolbox)
        self.stock_color_button.setObjectName("stock_color_button")
        self.verticalLayout_2.addWidget(self.stock_color_button, 0, QtCore.Qt.AlignTop)
        self.stock_size_button = QtWidgets.QPushButton(self.stock_toolbox)
        self.stock_size_button.setObjectName("stock_size_button")
        self.verticalLayout_2.addWidget(self.stock_size_button, 0, QtCore.Qt.AlignTop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.toolbox.addItem(self.stock_toolbox, "")
        self.forecast_toolbox = QtWidgets.QWidget()
        self.forecast_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.forecast_toolbox.setObjectName("forecast_toolbox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.forecast_toolbox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.forecast_filters_group = QtWidgets.QGroupBox(self.forecast_toolbox)
        self.forecast_filters_group.setObjectName("forecast_filters_group")
        self.formLayout_6 = QtWidgets.QFormLayout(self.forecast_filters_group)
        self.formLayout_6.setObjectName("formLayout_6")
        self.forecast_filters_prefixes_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_prefixes_label.setObjectName("forecast_filters_prefixes_label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_prefixes_label)
        self.forecast_filters_prefixes_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_prefixes_text.setObjectName("forecast_filters_prefixes_text")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_prefixes_text)
        self.forecast_filters_names_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_names_label.setObjectName("forecast_filters_names_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_names_label)
        self.forecast_filters_categories_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_categories_label.setObjectName("forecast_filters_categories_label")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_categories_label)
        self.forecast_filters_colors_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_colors_label.setObjectName("forecast_filters_colors_label")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_colors_label)
        self.forecast_filters_sizes_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_sizes_label.setObjectName("forecast_filters_sizes_label")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_sizes_label)
        self.forecast_filters_sexes_label = QtWidgets.QLabel(self.forecast_filters_group)
        self.forecast_filters_sexes_label.setObjectName("forecast_filters_sexes_label")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.forecast_filters_sexes_label)
        self.forecast_filters_names_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_names_text.setObjectName("forecast_filters_names_text")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_names_text)
        self.forecast_filters_categories_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_categories_text.setObjectName("forecast_filters_categories_text")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_categories_text)
        self.forecast_filters_colors_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_colors_text.setObjectName("forecast_filters_colors_text")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_colors_text)
        self.forecast_filters_sizes_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_sizes_text.setObjectName("forecast_filters_sizes_text")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_sizes_text)
        self.forecast_filters_sexes_text = QtWidgets.QLineEdit(self.forecast_filters_group)
        self.forecast_filters_sexes_text.setObjectName("forecast_filters_sexes_text")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.forecast_filters_sexes_text)
        self.verticalLayout_7.addWidget(self.forecast_filters_group, 0, QtCore.Qt.AlignTop)
        self.forecast_settings_group = QtWidgets.QGroupBox(self.forecast_toolbox)
        self.forecast_settings_group.setObjectName("forecast_settings_group")
        self.formLayout_2 = QtWidgets.QFormLayout(self.forecast_settings_group)
        self.formLayout_2.setObjectName("formLayout_2")
        self.forecast_settings_from_label = QtWidgets.QLabel(self.forecast_settings_group)
        self.forecast_settings_from_label.setObjectName("forecast_settings_from_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.forecast_settings_from_label)
        self.forecast_settings_from_spinbox = QtWidgets.QSpinBox(self.forecast_settings_group)
        self.forecast_settings_from_spinbox.setMinimum(3)
        self.forecast_settings_from_spinbox.setProperty("value", 90)
        self.forecast_settings_from_spinbox.setObjectName("forecast_settings_from_spinbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.forecast_settings_from_spinbox)
        self.forecast_settings_to_label = QtWidgets.QLabel(self.forecast_settings_group)
        self.forecast_settings_to_label.setObjectName("forecast_settings_to_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.forecast_settings_to_label)
        self.forecast_settings_to_spinbox = QtWidgets.QSpinBox(self.forecast_settings_group)
        self.forecast_settings_to_spinbox.setMinimum(1)
        self.forecast_settings_to_spinbox.setProperty("value", 24)
        self.forecast_settings_to_spinbox.setObjectName("forecast_settings_to_spinbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.forecast_settings_to_spinbox)
        self.forecast_season_label = QtWidgets.QLabel(self.forecast_settings_group)
        self.forecast_season_label.setObjectName("forecast_season_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.forecast_season_label)
        self.forecast_season_combo = QtWidgets.QComboBox(self.forecast_settings_group)
        self.forecast_season_combo.setObjectName("forecast_season_combo")
        self.forecast_season_combo.addItem("")
        self.forecast_season_combo.addItem("")
        self.forecast_season_combo.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.forecast_season_combo)
        self.verticalLayout_7.addWidget(self.forecast_settings_group, 0, QtCore.Qt.AlignTop)
        self.forecast_income_button = QtWidgets.QPushButton(self.forecast_toolbox)
        self.forecast_income_button.setObjectName("forecast_income_button")
        self.verticalLayout_7.addWidget(self.forecast_income_button)
        self.forecast_sales_button = QtWidgets.QPushButton(self.forecast_toolbox)
        self.forecast_sales_button.setObjectName("forecast_sales_button")
        self.verticalLayout_7.addWidget(self.forecast_sales_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.toolbox.addItem(self.forecast_toolbox, "")
        self.deliveries_toolbox = QtWidgets.QWidget()
        self.deliveries_toolbox.setObjectName("deliveries_toolbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.deliveries_toolbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.deliveries_filters_group = QtWidgets.QGroupBox(self.deliveries_toolbox)
        self.deliveries_filters_group.setObjectName("deliveries_filters_group")
        self.formLayout_7 = QtWidgets.QFormLayout(self.deliveries_filters_group)
        self.formLayout_7.setObjectName("formLayout_7")
        self.deliveries_filters_prefixes_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_prefixes_label.setObjectName("deliveries_filters_prefixes_label")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_prefixes_label)
        self.deliveries_filters_prefixes_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_prefixes_text.setObjectName("deliveries_filters_prefixes_text")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_prefixes_text)
        self.deliveries_filters_names_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_names_label.setObjectName("deliveries_filters_names_label")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_names_label)
        self.deliveries_filters_categories_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_categories_label.setObjectName("deliveries_filters_categories_label")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_categories_label)
        self.deliveries_filters_colors_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_colors_label.setObjectName("deliveries_filters_colors_label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_colors_label)
        self.deliveries_filters_sizes_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_sizes_label.setObjectName("deliveries_filters_sizes_label")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_sizes_label)
        self.deliveries_filters_sexes_label = QtWidgets.QLabel(self.deliveries_filters_group)
        self.deliveries_filters_sexes_label.setObjectName("deliveries_filters_sexes_label")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.deliveries_filters_sexes_label)
        self.deliveries_filters_names_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_names_text.setObjectName("deliveries_filters_names_text")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_names_text)
        self.deliveries_filters_categories_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_categories_text.setObjectName("deliveries_filters_categories_text")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_categories_text)
        self.deliveries_filters_colors_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_colors_text.setObjectName("deliveries_filters_colors_text")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_colors_text)
        self.deliveries_filters_sizes_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_sizes_text.setObjectName("deliveries_filters_sizes_text")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_sizes_text)
        self.deliveries_filters_sexes_text = QtWidgets.QLineEdit(self.deliveries_filters_group)
        self.deliveries_filters_sexes_text.setObjectName("deliveries_filters_sexes_text")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deliveries_filters_sexes_text)
        self.verticalLayout_8.addWidget(self.deliveries_filters_group, 0, QtCore.Qt.AlignTop)
        self.deliveries_button = QtWidgets.QPushButton(self.deliveries_toolbox)
        self.deliveries_button.setObjectName("deliveries_button")
        self.verticalLayout_8.addWidget(self.deliveries_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.toolbox.addItem(self.deliveries_toolbox, "")
        self.analysis_toolbox = QtWidgets.QWidget()
        self.analysis_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.analysis_toolbox.setObjectName("analysis_toolbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.analysis_toolbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.analysis_dates_group = QtWidgets.QGroupBox(self.analysis_toolbox)
        self.analysis_dates_group.setObjectName("analysis_dates_group")
        self.formLayout = QtWidgets.QFormLayout(self.analysis_dates_group)
        self.formLayout.setObjectName("formLayout")
        self.analysis_date_from_label = QtWidgets.QLabel(self.analysis_dates_group)
        self.analysis_date_from_label.setObjectName("analysis_date_from_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.analysis_date_from_label)
        self.analysis_date_from = QtWidgets.QDateEdit(self.analysis_dates_group)
        self.analysis_date_from.setMinimumDate(QtCore.QDate(2012, 1, 1))
        self.analysis_date_from.setObjectName("analysis_date_from")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.analysis_date_from)
        self.analysis_date_to_label = QtWidgets.QLabel(self.analysis_dates_group)
        self.analysis_date_to_label.setObjectName("analysis_date_to_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.analysis_date_to_label)
        self.analysis_date_to = QtWidgets.QDateEdit(self.analysis_dates_group)
        self.analysis_date_to.setMinimumDate(QtCore.QDate(2012, 1, 1))
        self.analysis_date_to.setDate(QtCore.QDate(2013, 1, 1))
        self.analysis_date_to.setObjectName("analysis_date_to")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.analysis_date_to)
        self.verticalLayout.addWidget(self.analysis_dates_group, 0, QtCore.Qt.AlignTop)
        self.analysis_colors_button = QtWidgets.QPushButton(self.analysis_toolbox)
        self.analysis_colors_button.setObjectName("analysis_colors_button")
        self.verticalLayout.addWidget(self.analysis_colors_button, 0, QtCore.Qt.AlignTop)
        self.analysis_sizes_button = QtWidgets.QPushButton(self.analysis_toolbox)
        self.analysis_sizes_button.setObjectName("analysis_sizes_button")
        self.verticalLayout.addWidget(self.analysis_sizes_button, 0, QtCore.Qt.AlignTop)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.toolbox.addItem(self.analysis_toolbox, "")
        self.stocktaking_toolbox = QtWidgets.QWidget()
        self.stocktaking_toolbox.setGeometry(QtCore.QRect(0, 0, 300, 561))
        self.stocktaking_toolbox.setObjectName("stocktaking_toolbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stocktaking_toolbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stocktaking_file_group = QtWidgets.QGroupBox(self.stocktaking_toolbox)
        self.stocktaking_file_group.setObjectName("stocktaking_file_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.stocktaking_file_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stocktaking_file_text = QtWidgets.QLineEdit(self.stocktaking_file_group)
        self.stocktaking_file_text.setObjectName("stocktaking_file_text")
        self.horizontalLayout_2.addWidget(self.stocktaking_file_text)
        self.stocktaking_file_button = QtWidgets.QToolButton(self.stocktaking_file_group)
        self.stocktaking_file_button.setObjectName("stocktaking_file_button")
        self.horizontalLayout_2.addWidget(self.stocktaking_file_button)
        self.verticalLayout_3.addWidget(self.stocktaking_file_group)
        self.stocktaking_button = QtWidgets.QPushButton(self.stocktaking_toolbox)
        self.stocktaking_button.setObjectName("stocktaking_button")
        self.verticalLayout_3.addWidget(self.stocktaking_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.toolbox.addItem(self.stocktaking_toolbox, "")
        self.horizontalLayout.addWidget(self.toolbox)
        self.line = QtWidgets.QFrame(self.central_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.main_widget = QtWidgets.QStackedWidget(self.central_widget)
        self.main_widget.setObjectName("main_widget")
        self.plot_page = QtWidgets.QWidget()
        self.plot_page.setObjectName("plot_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.plot_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_widget.addWidget(self.plot_page)
        self.table_page = QtWidgets.QWidget()
        self.table_page.setObjectName("table_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.table_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table = QtWidgets.QTableWidget(self.table_page)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.gridLayout_3.addWidget(self.table, 0, 0, 1, 1)
        self.main_widget.addWidget(self.table_page)
        self.horizontalLayout.addWidget(self.main_widget)
        main_window.setCentralWidget(self.central_widget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actionWczytaj_dane = QtWidgets.QAction(main_window)
        self.actionWczytaj_dane.setObjectName("actionWczytaj_dane")

        self.retranslateUi(main_window)
        self.toolbox.setCurrentIndex(4)
        self.forecast_season_combo.setCurrentIndex(2)
        self.main_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Analiza"))
        self.comparision_filters_group.setTitle(_translate("main_window", "Filtry"))
        self.comparision_filters_prefixes_label.setText(_translate("main_window", "Przedrostki ID"))
        self.comparision_filters_prefixes_text.setPlaceholderText(_translate("main_window", "prefix1, prefix2, ..."))
        self.comparision_filters_names_label.setText(_translate("main_window", "Nazwy"))
        self.comparision_filters_categories_label.setText(_translate("main_window", "Kategorie"))
        self.comparision_filters_colors_label.setText(_translate("main_window", "Kolory"))
        self.comparision_filters_sizes_label.setText(_translate("main_window", "Rozmiary"))
        self.comparision_filters_sexes_label.setText(_translate("main_window", "Płcie"))
        self.comparision_filters_names_text.setPlaceholderText(_translate("main_window", "nazwa1, nazwa2, ..."))
        self.comparision_filters_categories_text.setPlaceholderText(_translate("main_window", "kategoria1, kategoria2, ..."))
        self.comparision_filters_colors_text.setPlaceholderText(_translate("main_window", "kolor1, kolor2, ..."))
        self.comparision_filters_sizes_text.setPlaceholderText(_translate("main_window", "XS, S, M, L, XL, ONE_SIZE"))
        self.comparision_filters_sexes_text.setPlaceholderText(_translate("main_window", "man, woman, unisex"))
        self.comparision_periods_group.setTitle(_translate("main_window", "Okresy"))
        self.comparision_periods_text.setPlainText(_translate("main_window", "2014-01-01 2015-01-01\n"
"2015-01-01 2016-01-01\n"
"2016-01-01 2017-01-01"))
        self.comparision_income_button.setText(_translate("main_window", "Przychody"))
        self.comparision_costs_button.setText(_translate("main_window", "Koszty"))
        self.comparision_income_balance_button.setText(_translate("main_window", "Bilans dochodów"))
        self.comparision_sales_button.setText(_translate("main_window", "Sprzedaż"))
        self.comparision_resupply_button.setText(_translate("main_window", "Dostawy"))
        self.comparision_operations_balance_button.setText(_translate("main_window", "Bilans operacji"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.comparision_toolbox), _translate("main_window", "Porównanie okresów"))
        self.balance_incomes_button.setText(_translate("main_window", "Bilans dochodów"))
        self.balance_operations_button.setText(_translate("main_window", "Bilans operacji"))
        self.balance_year_group.setTitle(_translate("main_window", "Zakres lat"))
        self.balance_year_from_label.setText(_translate("main_window", "Rok od"))
        self.balance_year_to_label.setText(_translate("main_window", "Rok do"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.balance_toolbox), _translate("main_window", "Roczny bilans"))
        self.stock_filters_group.setTitle(_translate("main_window", "Filtry"))
        self.stock_filters_prefixes_label.setText(_translate("main_window", "Przedrostki ID"))
        self.stock_filters_prefixes_text.setPlaceholderText(_translate("main_window", "prefix1, prefix2, ..."))
        self.stock_filters_names_label.setText(_translate("main_window", "Nazwy"))
        self.stock_filters_names_text.setPlaceholderText(_translate("main_window", "nazwa1, nazwa2, ..."))
        self.stock_filters_categories_label.setText(_translate("main_window", "Kategorie"))
        self.stock_filters_categories_text.setPlaceholderText(_translate("main_window", "kategoria1, kategoria2, ..."))
        self.stock_filters_colors_label.setText(_translate("main_window", "Kolory"))
        self.stock_filters_colors_text.setPlaceholderText(_translate("main_window", "kolor1, kolor2, ..."))
        self.stock_filters_sizes_label.setText(_translate("main_window", "Rozmiary"))
        self.stock_filters_sizes_text.setPlaceholderText(_translate("main_window", "XS, S, M, L, XL, ONE_SIZE"))
        self.stock_filters_sexes_label.setText(_translate("main_window", "Płcie"))
        self.stock_filters_sexes_text.setPlaceholderText(_translate("main_window", "man, woman, unisex"))
        self.stock_date_group.setTitle(_translate("main_window", "Data"))
        self.stock_date.setDisplayFormat(_translate("main_window", "yyyy-MM-dd"))
        self.stock_color_button.setText(_translate("main_window", "Według koloru"))
        self.stock_size_button.setText(_translate("main_window", "Według rozmiaru"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.stock_toolbox), _translate("main_window", "Stan magazynu"))
        self.forecast_filters_group.setTitle(_translate("main_window", "Filtry"))
        self.forecast_filters_prefixes_label.setText(_translate("main_window", "Przedrostki ID"))
        self.forecast_filters_prefixes_text.setPlaceholderText(_translate("main_window", "prefix1, prefix2, ..."))
        self.forecast_filters_names_label.setText(_translate("main_window", "Nazwy"))
        self.forecast_filters_categories_label.setText(_translate("main_window", "Kategorie"))
        self.forecast_filters_colors_label.setText(_translate("main_window", "Kolory"))
        self.forecast_filters_sizes_label.setText(_translate("main_window", "Rozmiary"))
        self.forecast_filters_sexes_label.setText(_translate("main_window", "Płcie"))
        self.forecast_filters_names_text.setPlaceholderText(_translate("main_window", "nazwa1, nazwa2, ..."))
        self.forecast_filters_categories_text.setPlaceholderText(_translate("main_window", "kategoria1, kategoria2, ..."))
        self.forecast_filters_colors_text.setPlaceholderText(_translate("main_window", "kolor1, kolor2, ..."))
        self.forecast_filters_sizes_text.setPlaceholderText(_translate("main_window", "XS, S, M, L, XL, ONE_SIZE"))
        self.forecast_filters_sexes_text.setPlaceholderText(_translate("main_window", "man, woman, unisex"))
        self.forecast_settings_group.setTitle(_translate("main_window", "Ustawienia prognozy"))
        self.forecast_settings_from_label.setText(_translate("main_window", "Miesiące analizowane"))
        self.forecast_settings_to_label.setText(_translate("main_window", "Miesiące prognozowane"))
        self.forecast_season_label.setText(_translate("main_window", "Cykl sezonowości"))
        self.forecast_season_combo.setItemText(0, _translate("main_window", "3"))
        self.forecast_season_combo.setItemText(1, _translate("main_window", "6"))
        self.forecast_season_combo.setItemText(2, _translate("main_window", "12"))
        self.forecast_income_button.setText(_translate("main_window", "Prognoza przychodów"))
        self.forecast_sales_button.setText(_translate("main_window", "Prognoza sprzedaży"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.forecast_toolbox), _translate("main_window", "Prognoza"))
        self.deliveries_filters_group.setTitle(_translate("main_window", "Filtry"))
        self.deliveries_filters_prefixes_label.setText(_translate("main_window", "Przedrostki ID"))
        self.deliveries_filters_prefixes_text.setPlaceholderText(_translate("main_window", "prefix1, prefix2, ..."))
        self.deliveries_filters_names_label.setText(_translate("main_window", "Nazwy"))
        self.deliveries_filters_categories_label.setText(_translate("main_window", "Kategorie"))
        self.deliveries_filters_colors_label.setText(_translate("main_window", "Kolory"))
        self.deliveries_filters_sizes_label.setText(_translate("main_window", "Rozmiary"))
        self.deliveries_filters_sexes_label.setText(_translate("main_window", "Płcie"))
        self.deliveries_filters_names_text.setPlaceholderText(_translate("main_window", "nazwa1, nazwa2, ..."))
        self.deliveries_filters_categories_text.setPlaceholderText(_translate("main_window", "kategoria1, kategoria2, ..."))
        self.deliveries_filters_colors_text.setPlaceholderText(_translate("main_window", "kolor1, kolor2, ..."))
        self.deliveries_filters_sizes_text.setPlaceholderText(_translate("main_window", "XS, S, M, L, XL, ONE_SIZE"))
        self.deliveries_filters_sexes_text.setPlaceholderText(_translate("main_window", "man, woman, unisex"))
        self.deliveries_button.setText(_translate("main_window", "Wyświetl "))
        self.toolbox.setItemText(self.toolbox.indexOf(self.deliveries_toolbox), _translate("main_window", "Dostawy"))
        self.analysis_dates_group.setTitle(_translate("main_window", "Zakres dat"))
        self.analysis_date_from_label.setText(_translate("main_window", "Od"))
        self.analysis_date_from.setDisplayFormat(_translate("main_window", "yyyy-MM-dd"))
        self.analysis_date_to_label.setText(_translate("main_window", "Do"))
        self.analysis_date_to.setDisplayFormat(_translate("main_window", "yyyy-MM-dd"))
        self.analysis_colors_button.setText(_translate("main_window", "Najlepsze kolory"))
        self.analysis_sizes_button.setText(_translate("main_window", "Najlepsze rozmiary"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.analysis_toolbox), _translate("main_window", "Analiza"))
        self.stocktaking_file_group.setTitle(_translate("main_window", "Plik z danymi"))
        self.stocktaking_file_button.setText(_translate("main_window", "..."))
        self.stocktaking_button.setText(_translate("main_window", "Porównanie ze stanem"))
        self.toolbox.setItemText(self.toolbox.indexOf(self.stocktaking_toolbox), _translate("main_window", "Inwentaryzacja"))
        self.actionWczytaj_dane.setText(_translate("main_window", "Wczytaj dane"))

